# Shell variables
# Generated by 'wal'
wallpaper='/home/matija/Images/1432908749300.jpg'

# Special
background='#09040c'
foreground='#f3c98a'
cursor='#f3c98a'

# Colors
color0='#09040c'
color1='#2f12a2'
color2='#ab1319'
color3='#e72e27'
color4='#e7612e'
color5='#e51a25'
color6='#e98e38'
color7='#f3c98a'
color8='#aa8c60'
color9='#2f12a2'
color10='#ab1319'
color11='#e72e27'
color12='#e7612e'
color13='#e51a25'
color14='#e98e38'
color15='#f3c98a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
