# Shell variables
# Generated by 'wal'
wallpaper='/home/matija/Images/1359330091856.jpg'

# Special
background='#0a0a0a'
foreground='#d4d5d8'
cursor='#d4d5d8'

# Colors
color0='#0a0a0a'
color1='#2183e6'
color2='#e51a1a'
color3='#358ee8'
color4='#4b96eb'
color5='#5998ec'
color6='#738cef'
color7='#d4d5d8'
color8='#949597'
color9='#2183e6'
color10='#e51a1a'
color11='#358ee8'
color12='#4b96eb'
color13='#5998ec'
color14='#738cef'
color15='#d4d5d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
